### ISSUE TITLE
TextWrangler 4.5.3 does not allow adding the scala language

### ISSUE THREAD

**Issue by Loungagna** [scala/scala-dist#107]
I have tried to use the plist file given and followed the instructions.

Nevertheless, when I start TextWrangler, the languages shown in the preferences do not include scala. In addition, TextWrangler 4.5.3 does not allow adding its own language for a given extension, or for a new extension.

Thank you in advance for your help.

**Comment by adriaanm** [comment]
I'm sorry, but we don't have the resources to maintain the tool-support for Scala.
To make it clear that these files no longer ship with the Scala distribution,
I've moved them over to their own repo: https://github.com/scala/scala-tool-support.

Please re-open your issue there, or -- better yet -- become its maintainer
(please contact scala-internals@googlegroups.com)!
