### ISSUE TITLE
.deb lintian issues

### ISSUE THREAD

**Issue by naftoligug** [scala/scala-dist#135]
From https://bugs.launchpad.net/ubuntu/+source/scala/+bug/1126035/comments/9:

> It works as a workaround, but the quality of the upstream package is bad:
> 
> $ lintian Downloads/scala-2.11.0.deb
> W: scala: control-file-is-empty conffiles
> W: scala: copyright-without-copyright-notice
> E: scala: description-starts-with-package-name
> E: scala: maintainer-address-missing LAMP/EPFL and Typesafe, Inc.
> E: scala: depends-on-obsolete-package depends: openjdk-6-jre
> W: scala: symlink-should-be-relative usr/bin/fsc /usr/share/scala/bin/fsc
> W: scala: symlink-should-be-relative usr/bin/scala /usr/share/scala/bin/scala
> W: scala: symlink-should-be-relative usr/bin/scalac /usr/share/scala/bin/scalac
> W: scala: symlink-should-be-relative usr/bin/scaladoc /usr/share/scala/bin/scaladoc
> W: scala: symlink-should-be-relative usr/bin/scalap /usr/share/scala/bin/scalap
> W: scala: extra-license-file usr/share/doc/scala/LICENSE.md
> W: scala: extra-license-file usr/share/doc/scala/License.rtf
> W: scala: embedded-javascript-library usr/share/doc/scala/api/scala-compiler/lib/jquery.js
> 
> After that, Lintian just hangs (which makes it impossible to install it using software center).

**Comment by gkossakowski** [comment]
FYI: Most of Scala devs are on Mac so we are not familiar with details of Linux tools and ecosystem. However, we're thrilled to take patches.

**Comment by bkanuka** [comment]
Any issues with my pull request?

**Comment by adriaanm** [comment]
Fixed by #139
