### ISSUE TITLE
Emacs scala-mode compound enhancement

### ISSUE THREAD

**Issue by andreas-roehler** [scala/scala-dist#140]
Hi Guys,
would take pleasure to translate some exercises realised at 
https://launchpad.net/python-mode into scala-mode.

That would cover 
- having a menu-entry for every command
- menu display command-name and short help
- commands addressing the common syntactic forms like
  statement, block/loop, top-level etc.
- commands taking this forms: move over, copy, execute, delete etc.

Just to make up some agenda for discuss. Please tell should be rather urgent items at your table. Will deliver specific reports when ready.

**Comment by adriaanm** [comment]
I'm sorry, but we don't have the resources to maintain the tool-support for Scala.
To make it clear that these files no longer ship with the Scala distribution,
I've moved them over to their own repo: https://github.com/scala/scala-tool-support.

Please re-open your issue there, or -- better yet -- become its maintainer
(please contact scala-internals@googlegroups.com)!
