### ISSUE TITLE
Upgrade to latest sbt-native-packager

### ISSUE THREAD

**Issue by adriaanm** [scala/scala-dist#141]
I tried to move from current 0.6.4 to both 0.7.x and 0.8.x, but it breaks debian packaging: https://github.com/scala/scala-dist/commit/2035c468ab8e0021551b5115a43fe0845de43797 (see parent commits for other attempts, which all fail in the same way.)

/cc @muuki88

**Comment by muuki88** [comment]
I'm trying  to reproduce this on my locale machine and identify the error. 
The error seems to be in the `chmod` command, which is interesting as this
hasn't really changed. 

What java versions is scala-dist-11 build against?

**Comment by muuki88** [comment]
Hm. I cannot run `debian:packageBin`

``` scala
::::::::::::::::::::::::::::::::::::::::::::::
::          UNRESOLVED DEPENDENCIES         ::
::::::::::::::::::::::::::::::::::::::::::::::
:: org.scala-lang#scala-dist;1.0-2035c468ab8e0021551b5115a43fe0845de43797: not found
::::::::::::::::::::::::::::::::::::::::::::::
```

I'm on the `2.11.x` branch.

**Comment by adriaanm** [comment]
Thanks! You'll need to add the following resolver:

```
$ sbt -Dproject.version=2.11.5-1810ac0-nightly 
> set resolvers += "reltmp" at "http://private-repo.typesafe.com/typesafe/scala-release-temp/"
> s3Upload::mappings // dry run
```

**Comment by adriaanm** [comment]
(Note the edit in the above comment, you need to set the project version.)

**Comment by muuki88** [comment]
I'm getting an error as well, even though another one

```
Error running chmod 0644 /home/muki/Development/git/scala-dist/target/scala-2.11.5-1810ac0-nightly/usr/share/doc/scala/tools/css
```

This is a bit weird as something within the chmod fails :/

**Comment by muuki88** [comment]
well, I think I found the error and it's not `chmod` itself. The folders

```
usr/share/doc/scala/licenses 
usr/share/doc/scala/tools
```

are empty. This is why chmod fails. Now we have to figure out why they are empty.

**Comment by adriaanm** [comment]
Aha! Maybe something is wrong with the mapping? Thanks for digging into this!

**Comment by muuki88** [comment]
No problem. It seems some mappings are not staged correctly (so not copied).

**Comment by adriaanm** [comment]
I see. If there's a change we can make on the scala-dist side -- happy to do so and upgrade!

**Comment by muuki88** [comment]
Maybe I can make a Christmas present for scala-dist, but not promises ;)

**Comment by adriaanm** [comment]
:-) :christmas_tree:

**Comment by SethTisue** [comment]
#142 was reverted because of problems on Windows; reopening
