### ISSUE TITLE
Large installation size

### ISSUE THREAD

**Issue by jordancoll** [scala/scala-dist#144]
Currently, docs are distributed with the main release, making it particularly heavy. (~470MB)
I suggest extracting the docs to a separate package (scala-doc).

**Comment by jordancoll** [comment]
I'm working on adding supporting features to sbt-native-packager
sbt/sbt-native-packager/issues/477

**Comment by SethTisue** [comment]
<img width="767" alt="Screen Shot 2019-04-08 at 10 41 22 AM" src="https://user-images.githubusercontent.com/161079/55718277-e1fa3000-59ea-11e9-95b9-555f60601c42.png">

the others are smaller now, but why is the `.deb` still huge? if this concerns anyone, please open a new, .deb specific ticket
