### ISSUE TITLE
syntax highlighting for unix shebangs?

### ISSUE THREAD

**Issue by jstjohn** [scala/scala-dist#15]
This is pretty obscure, but you can run a scala script on the unix command line with a shebang header if it starts at the first line of input. These work if you do something like this at the very beginning of a program.

```
#!/bin/sh
exec scala -Xscript -Xlint -optimise -J-Xmx3g "$0" "$@" 
!#
```

Would it be easy to make a syntax highlighting thing where everything between the `#!` and `!#` if they are at the beginning of a line, and start on the first line of a program, are colored like a comment or something? That would be a nice addition.

**Comment by adriaanm** [comment]
I'm sorry, but we don't have the resources to maintain the tool-support for Scala.
To make it clear that these files no longer ship with the Scala distribution,
I've moved them over to their own repo: https://github.com/scala/scala-tool-support.

Please re-open your issue there, or -- better yet -- become its maintainer
(please contact scala-internals@googlegroups.com)!
