### ISSUE TITLE
Prepare release notes for Scala 2.12.0-M2

### ISSUE THREAD

**Issue by retronym** [scala/scala-dist#151]
/cc @lrytz 
- [ ] Java 8 is now mandatory. We are testing with 8u45 and recommend you use this version or later. We believe that some non deterministic failures during our early testing were due to [JDK-8058847](https://bugs.openjdk.java.net/browse/JDK-8058847). Thanks to Vaidas Pilkauskas for '[making the connection](https://groups.google.com/d/msg/scala-user/0GsO0Hv9yfA/NF941LpsqEAJ) to this bug!.
  - [ ] Show an example of the error you get when using Java 6 ("Unsupported major.minor version 52.0")
- [ ] indylambda: recap, status, demo
-  [ ] optimizer: recap, status, todo

**Comment by lrytz** [comment]
i started with a few edits yesterday: https://github.com/scala/make-release-notes/pull/148

**Comment by SethTisue** [comment]
Oops, I forgot about this. Perhaps the Java 8 details could have gone in, but oh well. In the interest of keeping the announcements themselves short, I think the indylambda and optimizer stuff would be well handled in future announcements by linking to documents such as https://github.com/scala/make-release-notes/blob/2.11.x/experimental-backend.md, as we did in the 2.11.7 announcement.
