### ISSUE TITLE
deprecation warnings ("object WixHelper is deprecated")

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dist#158]
since enabling `-deprecation` in compiling the build definition, we're seeing:

``` scala
[warn] /Users/tisue/scala-dist/project/Wix.scala:35: method generateComponentsAndDirectoryXml in object WixHelper is deprecated: Use higher level abstraction
[warn]     val (bin, binDirXml0) = generateComponentsAndDirectoryXml(stage / "bin")
[warn]                             ^
[warn] /Users/tisue/scala-dist/project/Wix.scala:36: method generateComponentsAndDirectoryXml in object WixHelper is deprecated: Use higher level abstraction
[warn]     val (doc, docDirXml)  = generateComponentsAndDirectoryXml(stage / "doc", "doc_")
[warn]                             ^
[warn] /Users/tisue/scala-dist/project/Wix.scala:37: method generateComponentsAndDirectoryXml in object WixHelper is deprecated: Use higher level abstraction
[warn]     val (lib, libDirXml)  = generateComponentsAndDirectoryXml(stage / "lib")
[warn]                             ^
[warn] /Users/tisue/scala-dist/project/Wix.scala:38: method generateComponentsAndDirectoryXml in object WixHelper is deprecated: Use higher level abstraction
[warn]     val (api, apiDirXml)  = generateComponentsAndDirectoryXml(stageApi / "api", "api_")
[warn]                             ^
```

it would be nice to address this, because then we could enable `-Xfatal-warnings` for the build definition

**Comment by SethTisue** [comment]
@muuki88 is this something you might be interested in addressing?

**Comment by muuki88** [comment]
Unfortunately I have no experience with the Windows stuff after all. The deprecation warning is pretty old though. @jsuereth introduced it almost 2 1/2 years ago. We can open an issue on sbt/sbt-native-packager and I can ping the two windows contributors if they have resources to fix this. 

Other option is to remove the deprecation.
- [initial commit](https://github.com/sbt/sbt-native-packager/commit/9a5375158db9dad07f8fccf8bdc15a23eefb24e5#diff-a531abcb94b88569582439598012fad0R233)
- [deprecation details](https://github.com/sbt/sbt-native-packager/commit/34cbfca1b3d0b347d0ef3033a06e269ff55088fd#diff-a531abcb94b88569582439598012fad0R241)

**Comment by SethTisue** [comment]
> I can ping the two windows contributors if they have resources to fix this

I'd appreciate that

**Comment by SethTisue** [comment]
if https://github.com/sbt/sbt-native-packager/pull/909 is merged, the warnings will go away when we eventually upgrade to that version, but it could be a while, as per #166
