### ISSUE TITLE
move to newer sbt-native-packager?

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dist#166]
we are leaving 2.11.x frozen at an old version, even for 2.11.9, in the interest of stability

Scala 2.12.0 was released using sbt-native-packager 1.0.6. so far, we haven't received any reports of regressions, knock on wood.

it's tempting to keep pushing forward to newer versions for 2.12.x, but it's also tempting to just leave it alone and figure we'll move to 1.1.0 or newer for Scala 2.13. we don't RC minor Scala releases anymore, so that argues for staying on 1.0.6 for a while, since there isn't a chance for users to catch regressions until after the release is already out the door. so that's my current leaning, is delay any upgrade until 2.13

cc @muuki88

**Comment by muuki88** [comment]
Most improvements in native-packager targeted the `JavaAppServerArchetype`. Only a few enhancements where for format plugins ( I saw the comments for the missing tar option in the build.sbt ).

All fixes that can be backported to the 1.1.x release line will be released. However my focus is on the refactorings for 1.2.x, which as far as I can tell, shouldn't affect this build.

**Comment by SethTisue** [comment]
PR #180
