### ISSUE TITLE
upgrading from sbt 0.13.9 to 0.13.13 broke scala-dist

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dist#171]
resulting in the Scala 2.12 nightly distribution having a 2.10 scala-library.jar (and probably other similarly wrong contents)

details on how I narrowed this down at https://github.com/scala/scala-dev/issues/281

but I don't know the specific cause yet beyond the sbt version number difference, that's next

**Comment by SethTisue** [comment]
bisect: 0.13.11 is good, 0.13.12 is bad

a look at the 0.13.12 changes at http://www.scala-sbt.org/0.13/docs/sbt-0.13-Tech-Previews.html makes me suspect "By default the Scala toolchain artifacts are now transitively resolved using the provided scalaVersion...", but only vaguely

**Comment by SethTisue** [comment]
a shorter reproduction:

```
sbt -Dsbt.override.build.repos=true -Dsbt.repository.config=/Users/tisue/scala-dist/conf/repositories -Dproject.version=2.12.1-ee1c02b-nightly universal:packageZipTarball
dtrx target/universal/scala-2.12.1-ee1c02b-nightly.tgz
unzip scala-2.12.1-ee1c02b-nightly/lib/scala-library.jar library.properties
cat library.properties
```

bypassing the Jenkins script means you don't have to wait for `$WORKSPACE/.ivy2` to populate

be sure to `git clean -fdX` in between testing this stuff

**Comment by SethTisue** [comment]
you don't need to actually run `packageZipTarBall`, it's enough to run `show universal:mappings`

with 0.13.11 the output includes `(/Users/tisue/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.1-ee1c02b-nightly.jar,lib/scala-library.jar)`

but with 0.13.12 you see `(/Users/tisue/.sbt/boot/scala-2.10.6/lib/scala-library.jar,lib/scala-library.jar)`

**Comment by SethTisue** [comment]
`universal:mappings` is constructed by a bunch of tricky code in `project/ScalaDist.scala`

hmm, could be the `dependencyOverrides` stuff in https://github.com/sbt/sbt/issues/2286? "There are zero situations where you should mix jars from different releases" says Paul, but we could be in such a situation here

**Comment by SethTisue** [comment]
it occurred to me that maybe the reason we're getting 2.10.6 is not that it's the Scala version being used to compile the build definition, but more simply because it's the default setting for `scalaVersion`

with both sbt 0.13.11 and 0.13.2,

```
> show scalaVersion
[info] 2.10.6
```

we hadn't bothered to set this because we didn't need to (we have no Scala sources in the project)

experimentally in the sbt shell, `set scalaVersion := "2.12.1-ee1c02b-nightly"` seems to fix the bad values in `universal:mappings`. I could only be so lucky that this actually works without me having to understand everything about 2286 and its sister tickets/PRs...

**Comment by adriaanm** [comment]
Was this caught by the smoketests? EDIT: ah, yes, it was according to https://github.com/scala/scala-dev/issues/281 -- great!
