### ISSUE TITLE
rpm available at official site has discrepancy between metadata vs filename

### ISSUE THREAD

**Issue by mvk** [scala/scala-dist#178]
I have downloaded the rpm from this page:
https://www.scala-lang.org/download/2.10.4.html

this is the link to the file: https://www.scala-lang.org/files/archive/scala-2.10.4.rpm
What I did:
1. pushed the file under `path/to/dir` in artifactory.
1. configured a `scala.repo` file with `baseurl=$artifactory_url/repo/simple/path/to/dir`
1. added `scala.repo` file with `yum-config-manager --add-repo scala.repo`
1. refreshed metadata `yum clean all && yum makecache`
1. tried installing with `sudo yumdownloader --resolve scala`
1. at the point where should download I'm getting an error.
```

Loaded plugins: product-id
--> Running transaction check
---> Package scala.noarch 0:2.10.4-400 will be installed
--> Finished Dependency Resolution
scala-2.10.4.rpm               FAILED.
http://myserver.local:8081/artifactory/simple/scala-local/2.10.4/2.10.4/RPMS/scala-2.10.4.rpm: [Errno 14] HTTP Error 404 - Not Found                                    ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.

To address this issue please refer to the below knowledge base article


https://access.redhat.com/articles/1320623

If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.

scala-2.10.4-400.noarch: [Errno 256] No more mirrors to try.
```

Further investigation shows the version is not `2.10.4`, but `2.10.4-400`, and there is architecture tag set to `noarch`, and the rpm original file name should have been `scala-2.10.40-400.noarch.rpm`
After renaming the file to that, and reuploading it to artifactory, refreshing the metadata there and locally, package installs. ok.

I expect the fact the "nice" file name is used - is the root cause.
If you want to publish with this nice name, you have to match the metadata.

**Comment by SethTisue** [comment]
is this still an issue?

**Comment by mvk** [comment]
HI, @SethTisue .
I reported this issue 2 years ago :)
if you are a maintainer you can try reproducing.

**Comment by SethTisue** [comment]
Closing since we don't have a recent confirmation. We can reopen if someone confirms the problem still exists in current Scala.
