### ISSUE TITLE
Create separate repo for vim plugin

### ISSUE THREAD

**Issue by grr** [scala/scala-dist#4]
Please create a separate repository for the vim plugin. This would allow it to be easily managed by the popular pathogen [1] and to keep it up to date as a git submodule [2].

[1] http://www.vim.org/scripts/script.php?script_id=2332
[2] http://www.allenwei.cn/tips-using-git-submodule-keep-your-plugin-up-to-date/

**Comment by jsuereth** [comment]
I'm fine doing so, but I'm not aware of any of these packages.  If we were to fork a vim plugin, would you be willing to maintain it?

**Comment by grr** [comment]
Not me, but maybe you can collaborate with @derekwyatt:
https://github.com/derekwyatt/vim-scala

**Comment by gokcehan** [comment]
I'm using `vundle` for plugin management and I can use these vim files using:

```
Bundle 'scala/scala-dist', {'rtp': 'tool-support/src/vim'}
```

It pulls in the whole repository but I'm fine with it. I haven't used pathogen for a long time but it might have a similar setting like this.

**Comment by bak** [comment]
@gokcehan That is so excellent. I'm going to go delete my vim-scala repo now.

**Comment by adriaanm** [comment]
I'm sorry, but we don't have the resources to maintain the tool-support for Scala.
To make it clear that these files no longer ship with the Scala distribution,
I've moved them over to their own repo: https://github.com/scala/scala-tool-support.

Please re-open your issue there, or -- better yet -- become its maintainer
(please contact scala-internals@googlegroups.com)!
