### ISSUE TITLE
Performance regression in emacs scala-mode

### ISSUE THREAD

**Issue by freels** [scala/scala-dist#46]
Commit 0a6a908640c56e204fe34795c38552389513bc2d introduced a performance regression which makes typing unbearably slow with a reasonably large source file.

**Comment by jsuereth** [comment]
@freels Would you mind testing the fix for me?  Thanks much!

**Comment by freels** [comment]
Sorry, just got to this. Seems to have been fixed, thanks @yuchangyuan!
