### ISSUE TITLE
Emacs: Syntax highlight on default arguments

### ISSUE THREAD

**Issue by andresilva** [scala/scala-dist#53]
The syntax highlighting stops working on functions with default arguments. 
Here's a screenshot to make it clear: http://bit.ly/OWdoBG

**Comment by adriaanm** [comment]
I'm sorry, but we don't have the resources to maintain the tool-support for Scala.
To make it clear that these files no longer ship with the Scala distribution,
I've moved them over to their own repo: https://github.com/scala/scala-tool-support.

Please re-open your issue there, or -- better yet -- become its maintainer
(please contact scala-internals@googlegroups.com)!

**Comment by SethTisue** [comment]
see also https://github.com/hvesalai/scala-mode2
