### ISSUE TITLE
Indentation in scala vim files

### ISSUE THREAD

**Issue by schmmd** [scala/scala-dist#6]
Shouldn't the scala vim files (tool-support/src/vim) set the shiftwidth and tabstop to 2?  I could be way off here, I'm not sure how this is usually done.  It does seem appropriate though, since the default indentation in scala is 2.

**Comment by jsuereth** [comment]
It should.  Would you like to submit a patch?

**Comment by schmmd** [comment]
Looks like this has already been done.  (https://github.com/scala/scala-dist/commit/ff1db35d53bb81777fb0a1c45015a60637987395)
