### ISSUE TITLE
Move gedit language specification upstream

### ISSUE THREAD

**Issue by pwithnall** [scala/scala-dist#67]
In order to prevent every user having to manually install the Scala language specification file in gedit, it would be great if it could be moved upstream.

This bug report is open about it upstream in gedit:
https://bugzilla.gnome.org/show_bug.cgi?id=684933

Moving it upstream requires that the language file (scala.lang, https://github.com/scala/scala-dist/blob/master/tool-support/src/gedit/scala.lang) be licenced under LGPLv2.1+.

The current licence of the file is unclear to me. If it’s not already licenced compatibly, would the authors (Gabriel Riba, fdietze, anthonykirby and Paul Phillips) mind relicencing it? Thanks!

**Comment by nacho** [comment]
The lang file is also missing the classes that should be added. i.e no-spell-check

**Comment by jsuereth** [comment]
Anyone who wants to help maintain this, please do!   Note: that all code is
under a modified BSD License, a.k.a. the Scala License.
- Josh

**Comment by nacho** [comment]
See that we will not accept any non lgpl lang file under our tree. So a relicensing is needed.

**Comment by jsuereth** [comment]
I'll see what I can do.

**Comment by nacho** [comment]
ping

**Comment by medovina** [comment]
Any update on this?  It would be really nice to have Scala highlighting available in gtksourceview (and, hence, gedit) by default.

**Comment by medovina** [comment]
Actually we want to put scala.lang in gtksourceview, which is the component that gedit uses for displaying and syntax highlighting source files.  And both gtksourceview and gedit are actually licensed under the GPL, not the LGPL.

Above jsuereth asserted that the scala-dist code is licensed under the Scala license:

https://github.com/scala/scala/blob/master/docs/LICENSE

The Scala license is very similar to the modified (3-clause) BSD license:

http://directory.fsf.org/wiki/License:BSD_3Clause

Note that the BSD license _is_ GPL-compatible.  This means that BSD-licensed code can be freely imported into a GPL project such as gtksourceview.  See http://www.gnu.org/licenses/license-list.html#ModifiedBSD .

I think the question, then, is whether the Scala license is also GPL-compatible.  I'm not an attorney, but I think it certainly is.  If you compare the Scala and BSD licenses you'll see that the differences are tiny and insignificant.

So I think there's no issue here.

**Comment by nacho** [comment]
See that we only accept LGPL languages on gtksourceview... so GPL is not an option

**Comment by medovina** [comment]
In an email discussion we received permission from all authors of existing lines in scala.lang (Min Huang, Felix Dietze, Anthony Kirby, Adam Dingle) to relicense under the LGPL.  I believe that means we can now close this.

**Comment by medovina** [comment]
scala.lang has now been pushed to gtksourceview:

https://git.gnome.org/browse/gtksourceview/commit/?id=efc8a9f8750fbe92f4362edde8c778b571a2f460

**Comment by Blaisorblade** [comment]
So this could indeed be closed, AFAICS. @jsuereth, could you take care of that?
