### ISSUE TITLE
I think xcode support is outdated?

### ISSUE THREAD

**Issue by tyoc213** [scala/scala-dist#68]
Hi there, I think https://github.com/scala/scala-dist/tree/master/tool-support/src/xcode is outdated, I don't find the path in my actual setup, not even this path `/Library/Application support/Apple/Developer Tools/`so I created this and `Specifications` I pasted the 2 files but nothing happens after computer restart it doesn't automatically open Xcode for *.scala files.

**Comment by jsuereth** [comment]
It's very possible it's outdated.   It's no longer included in the distribution due to lack of contributions/maintainers.

**Comment by adriaanm** [comment]
I'm sorry, but we don't have the resources to maintain the tool-support for Scala.
To make it clear that these files no longer ship with the Scala distribution,
I've moved them over to their own repo: https://github.com/scala/scala-tool-support.

Please re-open your issue there, or -- better yet -- become its maintainer
(please contact scala-internals@googlegroups.com)!
