### ISSUE TITLE
gedit support not working for me

### ISSUE THREAD

**Issue by Stefan-Wagner** [scala/scala-dist#79]
After downloading the scala.lang file to /usr/share/gtksourceview-3.0/language-specs I get the following errors:

---

<quote>
<code>
/usr/share/gtksourceview-3.0/language-specs/scala.lang:37: parser error : Specification mandate value for attribute data-pjax-transient
        <link data-pjax-transient rel='permalink' href='/scala/scala-dist/blob/8
                                  ^
/usr/share/gtksourceview-3.0/language-specs/scala.lang:37: parser error : attributes construct error
        <link data-pjax-transient rel='permalink' href='/scala/scala-dist/blob/8
                                  ^
/usr/share/gtksourceview-3.0/language-specs/scala.lang:37: parser error : Couldn't find end of Start Tag link
        <link data-pjax-transient rel='permalink' href='/scala/scala-dist/blob/8
                                  ^

(gedit:6181): GtkSourceView-WARNING **: Failed to parse '/usr/share/gtksourceview-3.0/language-specs/scala.lang'

(gedit:6181): GtkSourceView-WARNING **: Error reading language specification file '/usr/share/gtksourceview-3.0/language-specs/scala.lang'
/usr/share/gtksourceview-3.0/language-specs/scala.lang:37: parser error : Specification mandate value for attribute data-pjax-transient
        <link data-pjax-transient rel='permalink' href='/scala/scala-dist/blob/8
                                  ^
/usr/share/gtksourceview-3.0/language-specs/scala.lang:37: parser error : attributes construct error
        <link data-pjax-transient rel='permalink' href='/scala/scala-dist/blob/8
                                  ^
/usr/share/gtksourceview-3.0/language-specs/scala.lang:37: parser error : Couldn't find end of Start Tag link
        <link data-pjax-transient rel='permalink' href='/scala/scala-dist/blob/8
                                  ^

(gedit:6181): GtkSourceView-WARNING **: Failed to parse '/usr/share/gtksourceview-3.0/language-specs/scala.lang'

(gedit:6181): GtkSourceView-WARNING **: Error reading language specification file '/usr/share/gtksourceview-3.0/language-specs/scala.lang'
</code>
## </quote>

Gedit is version 3.4.1, which is the current version for Ubuntu 12.04 LTS. 

The version with gtksourceview-2.0 on my previous system worked well.

**Comment by adriaanm** [comment]
I'm sorry, but we don't have the resources to maintain the tool-support for Scala.
To make it clear that these files no longer ship with the Scala distribution,
I've moved them over to their own repo: https://github.com/scala/scala-tool-support.

Please re-open your issue there, or -- better yet -- become its maintainer
(please contact scala-internals@googlegroups.com)!
