### ISSUE TITLE
emacs Syntax highlighting missed end of comments: /* **/

### ISSUE THREAD

**Issue by thkoch2001** [scala/scala-dist#8]
I've encountered this issue with the file project/Sbt.scala in sbt. The syntax
highlighting misses the end of comments of the form /\* **/ so that the rest of
the file is highlighted as comment.

This can be reproduced with a two liner scala file:
/\* **/
val hello="world"

Regards, Thomas Koch

**Comment by folone** [comment]
#49 Fixes this.

**Comment by adriaanm** [comment]
I'm sorry, but we don't have the resources to maintain the tool-support for Scala.
To make it clear that these files no longer ship with the Scala distribution,
I've moved them over to their own repo: https://github.com/scala/scala-tool-support.

Please re-open your issue there, or -- better yet -- become its maintainer
(please contact scala-internals@googlegroups.com)!
