### ISSUE TITLE
Emacs scala-mode indent issue

### ISSUE THREAD

**Issue by linkenneth** [scala/scala-dist#88]
Currently, the Emacs scala-mode tool has bugs on my Emacs 23.3 in Ubuntu 12.04. I am using Evil, the Vi layer on top of Emacs, but the bug happens even in normal Emacs mode. For me, this code bugs out:

``` scala
object Main {
  def fibs(x : Int) = {
    stuff
  }
}
```

On the bracket closing `fibs`, if I type a newline, it would not indent and throw a (wrong-type-argument number-or-marker-p nil) error. Strangely, though, if I simply add a newline at the beginning of the entire file, there's no bug at all.

I went through the backtrace and found that it's the (char-before) at line 164 in scala-lambda-p in scala-mode-indent.el that was the problem. (char-before) returns nil if the pointer is out of range. I'm not sure why this would happen, but I've made a simple fix and it seems to work for me. Simply replace (char-before) with (preceding-char) on both lines 164 and 165. I don't believe there would be any side-effects from this, so I think this would be an easy fix. Could someone else double-check these bugs and the solution to them?

I'm somewhat new to helping out in these projects, so I'm not sure how to proceed. Should I send a pull request?

**Comment by adriaanm** [comment]
Thanks for the diagnosis and the fix! Sounds like you're ready for your first PR! Please have a look at the PR policy for the Scala project: https://github.com/scala/scala/wiki/Pull-Request-Policy, especially, we ask you to [sign the CLA](http://typesafe.com/contribute/cla/scala)

**Comment by linkenneth** [comment]
Thanks a lot! I'll do that in a bit. Did you double-check that there was a bug and that there were no unwanted side effects though?

**Comment by linkenneth** [comment]
Alright I've made the pull request at https://github.com/scala/scala-dist/pull/89.

**Comment by adriaanm** [comment]
I'm sorry, but we don't have the resources to maintain the tool-support for Scala.
To make it clear that these files no longer ship with the Scala distribution,
I've moved them over to their own repo: https://github.com/scala/scala-tool-support.

Please re-open your issue there, or -- better yet -- become its maintainer
(please contact scala-internals@googlegroups.com)!
