### ISSUE TITLE
scala emacs mode sets require-final-newline

### ISSUE THREAD

**Issue by thkoch2001** [scala/scala-dist#9]
Hi,

I've been editing sbt source code with emacs and every edited files has an additional change, a final newline. Please keep it configurable whether I'd like to add newlines. Or is there an important reason to have final newlines in scala souce code? In that case I'd raise this issue in the simple-build-tool.

Regards, Thomas Koch

https://github.com/scala/scala-dist/blob/master/tool-support/src/emacs/scala-mode.el#L189

**Comment by adriaanm** [comment]
I'm sorry, but we don't have the resources to maintain the tool-support for Scala.
To make it clear that these files no longer ship with the Scala distribution,
I've moved them over to their own repo: https://github.com/scala/scala-tool-support.

Please re-open your issue there, or -- better yet -- become its maintainer
(please contact scala-internals@googlegroups.com)!
