### ISSUE TITLE
Produces deb package without scala in it

### ISSUE THREAD

**Issue by teknotus** [scala/scala-dist#94]
Running scala-installer/debian:package-bin produced a 2k package. This obviously doesn't have the scala distribution in it. This might be a result of scala-dist.zip being in the wrong location, but this instructions say to put it in.

~/scala/scala-dist/target/tmp/scala-dist.zip

And it was there. No warnings were produced.

**Comment by adriaanm** [comment]
Fixed in 2.11. I'm sorry, but I don't have time to backport to 2.10.
